example:
  property: I AM THE DEV
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/eagle_eye_local
    username: gen
    password: postgres
    hikari:
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        proc:
          param_null_passing: true
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect